env:
  global:
  - secure: "iVRS23GxTD/1lQlc01N7HSQVdo3Q9IgOhoXK01zN9lQvNJzegEImPif+wlnWh5hXKtCt1xUe55xdFIoI4r+qdTzBRkDqHXYqfAPTGJUY3inc3l/e0LN7Jm8P5Y8cOD2N17hpDAoHj7xpl6jtsP1llPVYHyJ+Xvx5wfZCryiX3dMOVdh4pzLmTeLjl1MW8tW9KZPx3Q6ysEkpnE27Mm53VjnmrWx64tE6x3AC411IXDOOz4fzk1ysSkSlYo6v7ue84Th0Fj1QPDdT5AEumlolPzT3lovQWLTz4tGCfHvFcuYO6QWxu7WuXlq36bai1z/ppf3G15oe0l1uqv3CWFeQlaMGYvlwLvM1CowABsgGt/1wolpwOyYVkVfyKak86s8LcBGL1KYvXkJu820p8g+nYt0xIo+CkvVoSeh9CximB17Yogba6NuM0k20tCcSas0z7gcJUdeB8+QITQ4nk0/qVZ10YdvuzeK9EJm1EMt+oLvzCerCr3hK2iwfvVg1Fk29hKxTqIBa5WBVWv2EJlj+zmMoojuQQ0ly+zKfZ5P7zc99pDePtcfkzL+kbK/SLak6BIJ46pVgMfT/Rhm5hJ7kKJCCD6smlOqxscwbokdVHWlxS2ejSn1kHFbWCd0JP1n/GOO4rP4v4jbWGUOJQiIb9epnt8DsIPJn4flo8lOC5is="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "runtimeco/mcuboot"
      version: 1.0
      description: "Secure boot for 32-bit Microcontrollers!"
    notification_email: utzig@apache.org
    build_command: "make -f Makefile.coverity"
    branch_pattern: "coverity_scan"
