language: c
compiler:
  - gcc

env:
  global:
  - secure: "NFn42/AsRSpK3c+jIaLAC/hSfj8aqT3mIVmxrzucDIj7Nol89z0NIS1laVeqjwm0x1VQmZzedX8l8xJ7FozH09kC0mIySE6mwC4vfOd08jeB4AziMSxZIldfBCW7qhogdZhuaabsz8Vr9Ph/NTsVcKoazuYvrnqf/eiBVcFFzXFRRAAH+IHyVO9PaW+bGlOcYXsWPHPup0pPSCafP7unUta+o89zgGqQm8HwY6tgIJl7sqABjyaVf2N1+YfJxckykPNbxvl8EcANQje/MPO8Sk2TiulcNECxJHA5ahIxwwUo3ACJKK6JIF0gIAiSE487MTjAMwaMKfsgIGsW8RLTXLDj+AUx5Cl/OuZRaMwxswkjZAI+0mo2y1mjXrR+BqAUZEAX7vGVlX9jyE2oBo1ewA7qG/zay9Q0OjBsQ73xnsThErG8pstszWdSOoJw/ztYQx7jkWs4LbUfic+HJvCoF0t/RqpGAAI6zsFHiHXNqfyKI6k5VavV/TNC56HkEzRQTmottFi2lW8WGRtNnmwiF2SIUTtHA/2rxsue+E9mZ2jhGGi+uSdlCPYM1Apc3IvJoK4h0tlOVB7rI2Z3NB/C8lOL6+cN+WQ8YLEa63rtfoXLBl64p90sAKHqlh/badoJ7avqhuoHoXOzAUG5IJt2zW7zPFJYjuSwSMlF6lOkY7o="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "runtimeco/mcuboot"
      version: 1.0
      description: "Secure boot for 32-bit Microcontrollers!"
    notification_email: utzig@apache.org
    build_command: "make -f Makefile.coverity"
    branch_pattern: "coverity_scan"
